/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Game } from "./Game";
export * as factories from "./factories";
export { Game__factory } from "./factories/Game__factory";
