[features]
seeds = false
[programs.localnet]
solana_place = "PLACEMmfm3ZMpYKWfTwzHsTGnPnnDgmK2QkJPeLnZWE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
